require('dotenv').config()
const mongoose = require('mongoose')
const Sample = require('./models/Sample')

const records = [
  {
    id: 16, npid: 'NP-2022-016', autopsy_id: 'A22-016', mayo_clinic_id: 'MC-8812345',
    truncated_mayo_clinic_id: '2345', ptnum: 'PT-2022-016', irb_number: 'IRB-MCF-2018-0312',
    date_received: '2022-02-10', brain_source: 'Mayo Clinic Florida', study_source: 'MCJD Brain Bank',
    state_of_origin: 'Florida', dob: '1945-06-12', dod: '2022-02-09', age_at_death: 76,
    sex: 'Male', race: 'White', clinical_diagnosis: "Parkinson's disease with dementia",
    age_at_onset: 68, duration_years: 8, cognitive_status: 'Dementia',
    mmse_score: 12, cdr_score: 2, braak_stage: 5, thal_phase: 2, cerad_np: 'Sparse',
    abc_score: 'A1B3C1', a_score: 1, b_score: 3, c_score: 1,
    primary_diagnosis: "Parkinson's Disease", ad_type: null,
    lbd_type: 'Neocortical', cdlb_likelihood: 'High', tdp43: false,
    apoe: '33', mapt: 'H1/H1', rin: 6.1, brain_weight_grams: 1105,
    imaging_available: true, sleep_study_available: true,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Good',
      dna_extracted: true, rna_seq_available: false, blocks_available: 8,
      postmortem_interval_hours: 6.3, spinal_cord_available: true,
      olfactory_bulb_available: true, csf_available: false, unstained_slides_available: true,
      number_stained_slides: 20 }
  },
  {
    id: 17, npid: 'NP-2022-017', autopsy_id: 'A22-017', nacc_ptid: 'NACC-209341',
    ptnum: 'PT-2022-017', irb_number: 'IRB-BSH-2016-0044',
    date_received: '2022-05-03', brain_source: 'Banner Sun Health Research Institute',
    study_source: 'NIA ADC', state_of_origin: 'Arizona',
    dob: '1932-09-28', dod: '2022-05-02', age_at_death: 89,
    sex: 'Female', race: 'White', clinical_diagnosis: "Alzheimer's disease, probable",
    age_at_onset: 82, duration_years: 7, cognitive_status: 'Dementia',
    mmse_score: 3, cdr_score: 3, cdr_sb_score: 18, braak_stage: 6, thal_phase: 5,
    cerad_np: 'Frequent', abc_score: 'A3B3C3', a_score: 3, b_score: 3, c_score: 3,
    nia_reagan_score: 'High', primary_diagnosis: "Alzheimer's Disease", ad_type: 'Amnestic AD',
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: true, tdp_type: 'Type C',
    apoe: '44', mapt: 'H1/H1', rin: 5.8, brain_weight_grams: 998,
    imaging_available: false, sleep_study_available: false,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Fair',
      dna_extracted: true, rna_seq_available: true, blocks_available: 11,
      postmortem_interval_hours: 9.0, spinal_cord_available: false,
      olfactory_bulb_available: true, csf_available: false, unstained_slides_available: true,
      number_stained_slides: 28, freeze_thaw_times: 1 }
  },
  {
    id: 18, npid: 'NP-2022-018', autopsy_id: 'A22-018', nacc_ptid: 'NACC-310874',
    ptnum: 'PT-2022-018', irb_number: 'IRB-BSH-2016-0044',
    date_received: '2022-07-19', brain_source: 'Banner Sun Health Research Institute',
    study_source: 'NIA ADC', state_of_origin: 'Arizona',
    dob: '1958-03-11', dod: '2022-07-18', age_at_death: 64,
    sex: 'Male', race: 'Hispanic or Latino', clinical_diagnosis: 'Frontotemporal dementia, behavioral variant',
    age_at_onset: 59, duration_years: 5, cognitive_status: 'Dementia',
    mmse_score: 18, cdr_score: 1, braak_stage: 2, thal_phase: 1, cerad_np: 'None',
    abc_score: 'A0B1C0', a_score: 0, b_score: 1, c_score: 0,
    primary_diagnosis: 'Frontotemporal Dementia', ad_type: null,
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: true, tdp_type: 'Type B',
    apoe: '23', mapt: 'H1/H2', rin: 7.4, brain_weight_grams: 1198,
    imaging_available: true, sleep_study_available: false,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Excellent',
      dna_extracted: true, rna_seq_available: true, blocks_available: 14,
      postmortem_interval_hours: 4.1, spinal_cord_available: true,
      olfactory_bulb_available: false, csf_available: true, unstained_slides_available: true,
      number_stained_slides: 16, freeze_thaw_times: 0 }
  },
  {
    id: 19, npid: 'NP-2022-019', autopsy_id: 'A22-019', mayo_clinic_id: 'MC-7741920',
    truncated_mayo_clinic_id: '1920', ptnum: 'PT-2022-019', irb_number: 'IRB-MCF-2018-0312',
    date_received: '2022-09-30', brain_source: 'Mayo Clinic Florida', study_source: 'MCJD Brain Bank',
    state_of_origin: 'Florida', dob: '1940-12-25', dod: '2022-09-29', age_at_death: 81,
    sex: 'Female', race: 'Black or African American', clinical_diagnosis: 'Normal cognition',
    cognitive_status: 'Normal', mmse_score: 29, cdr_score: 0, braak_stage: 1, thal_phase: 0,
    cerad_np: 'None', abc_score: 'A0B1C0', a_score: 0, b_score: 1, c_score: 0,
    primary_diagnosis: 'Control', ad_type: null,
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: false,
    apoe: '33', mapt: 'H1/H2', rin: 8.1, brain_weight_grams: 1265,
    imaging_available: true, sleep_study_available: false,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Excellent',
      dna_extracted: true, rna_seq_available: true, blocks_available: 10,
      postmortem_interval_hours: 3.8, spinal_cord_available: true,
      olfactory_bulb_available: true, csf_available: true, unstained_slides_available: true,
      number_stained_slides: 22, freeze_thaw_times: 0 }
  },
  {
    id: 20, npid: 'NP-2023-020', autopsy_id: 'A23-020', nacc_ptid: 'NACC-412055',
    ptnum: 'PT-2023-020', irb_number: 'IRB-BSH-2016-0044',
    date_received: '2023-01-11', brain_source: 'Banner Sun Health Research Institute',
    study_source: 'NIA ADC', state_of_origin: 'Arizona',
    dob: '1947-08-04', dod: '2023-01-10', age_at_death: 75,
    sex: 'Male', race: 'White', clinical_diagnosis: "Alzheimer's disease with Lewy bodies",
    age_at_onset: 70, duration_years: 5, cognitive_status: 'Dementia',
    mmse_score: 9, cdr_score: 2, cdr_sb_score: 11, braak_stage: 5, thal_phase: 4,
    cerad_np: 'Moderate', abc_score: 'A2B3C2', a_score: 2, b_score: 3, c_score: 2,
    nia_reagan_score: 'High', primary_diagnosis: "Alzheimer's Disease", ad_type: 'Mixed AD',
    lbd_type: 'Limbic', cdlb_likelihood: 'Intermediate', tdp43: false,
    apoe: '34', mapt: 'H1/H1', rin: 6.6, brain_weight_grams: 1133,
    imaging_available: true, sleep_study_available: true,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Good',
      dna_extracted: true, rna_seq_available: true, blocks_available: 9,
      postmortem_interval_hours: 7.2, spinal_cord_available: false,
      olfactory_bulb_available: true, csf_available: false, unstained_slides_available: true,
      number_stained_slides: 30, freeze_thaw_times: 1 }
  },
  {
    id: 21, npid: 'NP-2023-021', autopsy_id: 'A23-021', mayo_clinic_id: 'MC-9023456',
    truncated_mayo_clinic_id: '3456', ptnum: 'PT-2023-021', irb_number: 'IRB-MCF-2018-0312',
    date_received: '2023-03-22', brain_source: 'Mayo Clinic Florida', study_source: 'MCJD Brain Bank',
    state_of_origin: 'Georgia', dob: '1953-01-17', dod: '2023-03-21', age_at_death: 70,
    sex: 'Female', race: 'Asian', clinical_diagnosis: 'Mild cognitive impairment, amnestic multidomain',
    age_at_onset: 67, duration_years: 3, cognitive_status: 'MCI',
    mmse_score: 24, moca_score: 20, cdr_score: 0.5, cdr_sb_score: 3,
    braak_stage: 3, thal_phase: 2, cerad_np: 'Sparse', abc_score: 'A2B2C1',
    a_score: 2, b_score: 2, c_score: 1,
    primary_diagnosis: 'Mild Cognitive Impairment', ad_type: null,
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: false,
    apoe: '23', mapt: 'H1/H2', rin: 7.0, brain_weight_grams: 1241,
    imaging_available: true, sleep_study_available: false,
    tissue: { ffpe_available: true, frozen_available: false,
      dna_extracted: true, rna_seq_available: false, blocks_available: 6,
      postmortem_interval_hours: 5.5, spinal_cord_available: false,
      olfactory_bulb_available: false, csf_available: false, unstained_slides_available: true,
      number_stained_slides: 14 }
  },
  {
    id: 22, npid: 'NP-2023-022', autopsy_id: 'A23-022', nacc_ptid: 'NACC-519832',
    ptnum: 'PT-2023-022', irb_number: 'IRB-BSH-2016-0044',
    date_received: '2023-06-05', brain_source: 'Banner Sun Health Research Institute',
    study_source: 'NIA ADC', state_of_origin: 'Arizona',
    dob: '1936-05-30', dod: '2023-06-04', age_at_death: 87,
    sex: 'Male', race: 'White', clinical_diagnosis: 'Lewy body dementia',
    age_at_onset: 81, duration_years: 6, cognitive_status: 'Dementia',
    mmse_score: 6, cdr_score: 3, braak_stage: 4, thal_phase: 3, cerad_np: 'Moderate',
    abc_score: 'A2B2C2', a_score: 2, b_score: 2, c_score: 2,
    primary_diagnosis: 'Lewy Body Dementia', ad_type: null,
    pd_braak_stage: 6, lbd_type: 'Neocortical', cdlb_likelihood: 'High', tdp43: false,
    apoe: '33', mapt: 'H1/H1', rin: 5.3, brain_weight_grams: 1078,
    imaging_available: true, sleep_study_available: true,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Fair',
      dna_extracted: true, rna_seq_available: false, blocks_available: 7,
      postmortem_interval_hours: 11.0, spinal_cord_available: true,
      olfactory_bulb_available: true, csf_available: false, unstained_slides_available: false,
      number_stained_slides: 18, freeze_thaw_times: 2 }
  },
  {
    id: 23, npid: 'NP-2023-023', autopsy_id: 'A23-023', mayo_clinic_id: 'MC-8834567',
    truncated_mayo_clinic_id: '4567', ptnum: 'PT-2023-023', irb_number: 'IRB-MCF-2018-0312',
    date_received: '2023-08-14', brain_source: 'Mayo Clinic Florida', study_source: 'MCJD Brain Bank',
    state_of_origin: 'Florida', dob: '1944-11-02', dod: '2023-08-13', age_at_death: 78,
    sex: 'Female', race: 'Black or African American', clinical_diagnosis: "Alzheimer's disease, possible",
    age_at_onset: 72, duration_years: 6, cognitive_status: 'Dementia',
    mmse_score: 14, cdr_score: 1, cdr_sb_score: 7.5, braak_stage: 4, thal_phase: 4,
    cerad_np: 'Moderate', abc_score: 'A2B2C2', a_score: 2, b_score: 2, c_score: 2,
    nia_reagan_score: 'Intermediate', primary_diagnosis: "Alzheimer's Disease", ad_type: 'Non-Amnestic AD',
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: true, tdp_type: 'Type A',
    apoe: '33', mapt: 'H1/H1', rin: 6.4, brain_weight_grams: 1155,
    imaging_available: false, sleep_study_available: false,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Good',
      dna_extracted: false, rna_seq_available: false, blocks_available: 5,
      postmortem_interval_hours: 8.7, spinal_cord_available: false,
      olfactory_bulb_available: false, csf_available: false, unstained_slides_available: true,
      number_stained_slides: 12, freeze_thaw_times: 0 }
  },
  {
    id: 24, npid: 'NP-2023-024', autopsy_id: 'A23-024', nacc_ptid: 'NACC-621109',
    ptnum: 'PT-2023-024', irb_number: 'IRB-BSH-2016-0044',
    date_received: '2023-10-28', brain_source: 'Banner Sun Health Research Institute',
    study_source: 'NIA ADC', state_of_origin: 'Arizona',
    dob: '1963-07-19', dod: '2023-10-27', age_at_death: 60,
    sex: 'Male', race: 'Hispanic or Latino', clinical_diagnosis: 'Normal cognition',
    cognitive_status: 'Normal', mmse_score: 30, cdr_score: 0, braak_stage: 0, thal_phase: 0,
    cerad_np: 'None', abc_score: 'A0B0C0', a_score: 0, b_score: 0, c_score: 0,
    primary_diagnosis: 'Control', ad_type: null,
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: false,
    apoe: '23', mapt: 'H1/H2', rin: 8.5, brain_weight_grams: 1380,
    imaging_available: true, sleep_study_available: false,
    tissue: { ffpe_available: false, frozen_available: true, frozen_tissue_quality: 'Excellent',
      dna_extracted: true, rna_seq_available: true, blocks_available: 4,
      postmortem_interval_hours: 2.9, spinal_cord_available: true,
      olfactory_bulb_available: true, csf_available: true, unstained_slides_available: false,
      number_stained_slides: 8, freeze_thaw_times: 0 }
  },
  {
    id: 25, npid: 'NP-2024-025', autopsy_id: 'A24-025', mayo_clinic_id: 'MC-9145678',
    truncated_mayo_clinic_id: '5678', ptnum: 'PT-2024-025', irb_number: 'IRB-MCF-2018-0312',
    date_received: '2024-01-09', brain_source: 'Mayo Clinic Florida', study_source: 'MCJD Brain Bank',
    state_of_origin: 'Florida', dob: '1939-04-07', dod: '2024-01-08', age_at_death: 84,
    sex: 'Female', race: 'White', clinical_diagnosis: "Alzheimer's disease, probable",
    age_at_onset: 78, duration_years: 6, cognitive_status: 'Dementia',
    mmse_score: 5, cdr_score: 3, cdr_sb_score: 17, braak_stage: 6, thal_phase: 5,
    cerad_np: 'Frequent', abc_score: 'A3B3C3', a_score: 3, b_score: 3, c_score: 3,
    nia_reagan_score: 'High', primary_diagnosis: "Alzheimer's Disease", ad_type: 'Amnestic AD',
    lbd_type: 'None', cdlb_likelihood: 'No LBD', tdp43: false,
    apoe: '34', mapt: 'H1/H1', rin: 7.3, brain_weight_grams: 1021,
    imaging_available: true, sleep_study_available: false,
    tissue: { ffpe_available: true, frozen_available: true, frozen_tissue_quality: 'Good',
      dna_extracted: true, rna_seq_available: true, blocks_available: 13,
      postmortem_interval_hours: 6.0, spinal_cord_available: true,
      olfactory_bulb_available: true, csf_available: false, unstained_slides_available: true,
      number_stained_slides: 32, freeze_thaw_times: 0 }
  },
]

mongoose.connect(process.env.DATABASE_URL).then(async () => {
  const result = await Sample.insertMany(records)
  console.log(`Inserted ${result.length} records (ids ${records[0].id}–${records[records.length-1].id})`)
  mongoose.disconnect()
}).catch(err => {
  console.error('Error:', err.message)
  process.exit(1)
})
